# Generated by Django 5.2.8 on 2025-12-04 18:11

from decimal import Decimal

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AmadeusSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Amadeus Configuration", max_length=50),
                ),
                ("client_id", models.CharField(max_length=100, verbose_name="API Key")),
                (
                    "client_secret",
                    models.CharField(max_length=100, verbose_name="API Secret"),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("test", "Test / Sandbox"),
                            ("production", "Live / Production"),
                        ],
                        default="test",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amadeus API Settings",
                "verbose_name_plural": "Amadeus API Settings",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                ("passport", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("contact", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WhatsAppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Configuration", max_length=50)),
                (
                    "api_url",
                    models.URLField(help_text="e.g. https://api.ultramsg.com/..."),
                ),
                ("api_token", models.CharField(max_length=200)),
                (
                    "template_tn",
                    models.TextField(
                        default="عسلامة {client_name}...\n{link}",
                        verbose_name="Message (Tunisian)",
                    ),
                ),
                (
                    "template_fr",
                    models.TextField(
                        default="Bonjour {client_name}...\n{link}",
                        verbose_name="Message (Français)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "WhatsApp Settings",
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "ℹ️ Info"),
                            ("medium", "⚠️ Important"),
                            ("high", "🚨 Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ManyToManyField(
                        blank=True,
                        editable=False,
                        related_name="acknowledged_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.CharField(blank=True, max_length=30, unique=True)),
                (
                    "visa_form_config",
                    models.JSONField(
                        blank=True,
                        default=core.models.default_visa_fields,
                        verbose_name="Public Form Fields",
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("ticket", "✈️ Air Ticket"),
                            ("hotel_out", "🏨 Outgoing Hotel"),
                            ("hotel_loc", "🇹🇳 Local Hotel"),
                            ("umrah", "🕋 Umrah Package"),
                            ("trip", "🚌 Organized Trip"),
                            ("tour", "🗺️ Tours"),
                            ("visa_app", "Visa Application"),
                            ("transfer", "🚖 Transfer"),
                            ("dummy", "📄 Dummy Booking"),
                        ],
                        max_length=40,
                        verbose_name="Service Type",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("issue", "Issue / New Sale"),
                            ("change", "Change / Amendment"),
                            ("refund", "Refund / Reversal"),
                        ],
                        default="issue",
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quote", "📝 Quote / Draft"),
                            ("confirmed", "✅ Confirmed"),
                            ("cancelled", "🚫 Cancelled"),
                        ],
                        default="quote",
                        max_length=20,
                        verbose_name="Booking Status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("advance", "Partial / Advance"),
                            ("paid", "Fully Paid"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled (Void)"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Sale Price / Fee",
                    ),
                ),
                (
                    "supplier_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Supplier Cost",
                    ),
                ),
                (
                    "refund_amount_client",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount we give back to client",
                        max_digits=12,
                        verbose_name="Refund TO Client",
                    ),
                ),
                (
                    "refund_amount_supplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount received back from supplier",
                        max_digits=12,
                        verbose_name="Refund FROM Supplier",
                    ),
                ),
                (
                    "is_ledger_posted",
                    models.BooleanField(
                        default=False, help_text="System Flag: Ledger entries created"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booked_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to original booking for Change/Refund",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendments",
                        to="core.booking",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_paste_data", models.TextField(blank=True)),
                ("airline_code", models.CharField(blank=True, max_length=10)),
                ("flight_number", models.CharField(blank=True, max_length=10)),
                ("departure_city", models.CharField(blank=True, max_length=10)),
                ("arrival_city", models.CharField(blank=True, max_length=10)),
                ("real_departure_date", models.DateField(blank=True, null=True)),
                ("departure_time", models.CharField(blank=True, max_length=10)),
                ("arrival_time", models.CharField(blank=True, max_length=10)),
                ("pnr_ref", models.CharField(default="XJ9K2M", max_length=10)),
                ("live_status", models.CharField(default="Unknown", max_length=50)),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket",
                        to="core.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalBooking",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("ref", models.CharField(blank=True, db_index=True, max_length=30)),
                (
                    "visa_form_config",
                    models.JSONField(
                        blank=True,
                        default=core.models.default_visa_fields,
                        verbose_name="Public Form Fields",
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("ticket", "✈️ Air Ticket"),
                            ("hotel_out", "🏨 Outgoing Hotel"),
                            ("hotel_loc", "🇹🇳 Local Hotel"),
                            ("umrah", "🕋 Umrah Package"),
                            ("trip", "🚌 Organized Trip"),
                            ("tour", "🗺️ Tours"),
                            ("visa_app", "Visa Application"),
                            ("transfer", "🚖 Transfer"),
                            ("dummy", "📄 Dummy Booking"),
                        ],
                        max_length=40,
                        verbose_name="Service Type",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("issue", "Issue / New Sale"),
                            ("change", "Change / Amendment"),
                            ("refund", "Refund / Reversal"),
                        ],
                        default="issue",
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quote", "📝 Quote / Draft"),
                            ("confirmed", "✅ Confirmed"),
                            ("cancelled", "🚫 Cancelled"),
                        ],
                        default="quote",
                        max_length=20,
                        verbose_name="Booking Status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("advance", "Partial / Advance"),
                            ("paid", "Fully Paid"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled (Void)"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Sale Price / Fee",
                    ),
                ),
                (
                    "supplier_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Supplier Cost",
                    ),
                ),
                (
                    "refund_amount_client",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount we give back to client",
                        max_digits=12,
                        verbose_name="Refund TO Client",
                    ),
                ),
                (
                    "refund_amount_supplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount received back from supplier",
                        max_digits=12,
                        verbose_name="Refund FROM Supplier",
                    ),
                ),
                (
                    "is_ledger_posted",
                    models.BooleanField(
                        default=False, help_text="System Flag: Ledger entries created"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_booking",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Link to original booking for Change/Refund",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical booking",
                "verbose_name_plural": "historical bookings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPayment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("BANK", "Bank Transfer"),
                            ("MOBILE", "Mobile Money"),
                            ("CHECK", "Check"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical payment",
                "verbose_name_plural": "historical payments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("outgoing", "Outgoing"),
                            ("locale", "Locale"),
                            ("billetterie", "Billetterie"),
                            ("omra", "Omra"),
                            ("voyages", "Voyages organisés"),
                            ("circuits", "circuits"),
                            ("visas", "Visas"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                ("summary", models.TextField(verbose_name="Résumé")),
                ("objective", models.TextField(blank=True, verbose_name="Objectif")),
                (
                    "prerequisites",
                    models.TextField(blank=True, verbose_name="Pré-requis"),
                ),
                ("procedure", models.TextField(verbose_name="Procédure détaillée")),
                ("example", models.TextField(blank=True, verbose_name="Exemple")),
                (
                    "escalation_contact",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Contact Escalade"
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=200, verbose_name="Tags"),
                ),
                (
                    "utility_score",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                        verbose_name="Utilité",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Knowledge Base",
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("account", models.CharField(max_length=100)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("BANK", "Bank Transfer"),
                            ("MOBILE", "Mobile Money"),
                            ("CHECK", "Check"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.booking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalExpense",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("paid", models.BooleanField(default=False)),
                ("recurrence", models.CharField(blank=True, max_length=20, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical expense",
                "verbose_name_plural": "historical expenses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("paid", models.BooleanField(default=False)),
                ("recurrence", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisaApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Full Name"
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(max_length=50, verbose_name="Passport Number"),
                ),
                ("photo", models.ImageField(upload_to="visas/photos/")),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nationality",
                    ),
                ),
                (
                    "passport_issue_date",
                    models.DateField(blank=True, null=True, verbose_name="Issue Date"),
                ),
                (
                    "passport_expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
                ),
                ("has_previous_visa", models.BooleanField(default=False)),
                ("previous_visa_details", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "travel_reason",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("itinerary", models.TextField(blank=True, null=True)),
                (
                    "ticket_departure",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "ticket_return",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "travel_insurance",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "accommodation_type",
                    models.CharField(
                        blank=True, default="hotel", max_length=20, null=True
                    ),
                ),
                ("host_name", models.CharField(blank=True, max_length=200, null=True)),
                ("host_address", models.TextField(blank=True, null=True)),
                ("host_phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "host_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "host_relationship",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("hotel_name", models.CharField(blank=True, max_length=200, null=True)),
                ("hotel_address", models.TextField(blank=True, null=True)),
                (
                    "hotel_reservation",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "payer",
                    models.CharField(
                        blank=True, default="self", max_length=20, null=True
                    ),
                ),
                ("guarantor_details", models.TextField(blank=True, null=True)),
                (
                    "financial_proofs",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("emergency_contact", models.TextField(blank=True, null=True)),
                ("consent_accurate", models.BooleanField(default=False)),
                ("consent_data", models.BooleanField(default=False)),
                ("consent_send_docs", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_data",
                        to="core.booking",
                    ),
                ),
            ],
        ),
    ]
