# Generated by Django 5.2.8 on 2025-11-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_supplier_paid",
            field=models.BooleanField(
                default=False,
                help_text="System flag: True if supplier cost has been deducted from ledger",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(
                choices=[
                    ("outgoing_hotel", "Outgoing Hotel"),
                    ("local_hotel", "Local Hotel"),
                    ("omra", "Omra"),
                    ("trip", "Trip"),
                    ("visa_app", "Visa / Services - Application"),
                    ("visa_dummy", "Visa / Services - Dummy Booking"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("advance", "Advance"),
                    ("confirmed", "Confirmed"),
                    ("change", "Change"),
                    ("refund", "Refund"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
