# Generated by Django 5.2.8 on 2025-12-04 18:43

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpayment",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("payment", "💰 Payment Received"),
                    ("refund", "💸 Refund Issued"),
                ],
                default="payment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="entry_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sale_revenue", "Sale Revenue"),
                    ("customer_payment", "Customer Payment"),
                    ("customer_refund", "Customer Refund"),
                    ("supplier_cost", "Supplier Cost"),
                    ("supplier_payment", "Supplier Payment"),
                ],
                help_text="Strict classification for reports",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("payment", "💰 Payment Received"),
                    ("refund", "💸 Refund Issued"),
                ],
                default="payment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("advance", "Partial / Advance"),
                    ("paid", "Fully Paid"),
                    ("overpaid", "Overpaid (Credit)"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Payment Status",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="refund_amount_client",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Legacy field - use Refunds action instead",
                max_digits=12,
                verbose_name="Refund TO Client",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="refund_amount_supplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Legacy field",
                max_digits=12,
                verbose_name="Refund FROM Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("quote", "📝 Quote"),
                    ("draft", "🚧 Draft"),
                    ("confirmed", "✅ Confirmed"),
                    ("cancelled", "🚫 Cancelled"),
                ],
                default="quote",
                max_length=20,
                verbose_name="Booking Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("advance", "Partial / Advance"),
                    ("paid", "Fully Paid"),
                    ("overpaid", "Overpaid (Credit)"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Payment Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="refund_amount_client",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Legacy field - use Refunds action instead",
                max_digits=12,
                verbose_name="Refund TO Client",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="refund_amount_supplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Legacy field",
                max_digits=12,
                verbose_name="Refund FROM Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("quote", "📝 Quote"),
                    ("draft", "🚧 Draft"),
                    ("confirmed", "✅ Confirmed"),
                    ("cancelled", "🚫 Cancelled"),
                ],
                default="quote",
                max_length=20,
                verbose_name="Booking Status",
            ),
        ),
    ]
