# Generated by Django 5.2.8 on 2025-12-05 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_historicalpayment_transaction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="supplier_payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "🔴 Unpaid"),
                    ("partial", "🟠 Partially Paid"),
                    ("paid", "🟢 Paid"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="Supplier Payment Status",
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="supplier_payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "🔴 Unpaid"),
                    ("partial", "🟠 Partially Paid"),
                    ("paid", "🟢 Paid"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="Supplier Payment Status",
            ),
        ),
        migrations.CreateModel(
            name="BookingLedgerAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="How much of this payment covers this specific booking",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        help_text="The booking debt being paid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_allocations",
                        to="core.booking",
                    ),
                ),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        help_text="The actual payment record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="core.ledgerentry",
                    ),
                ),
            ],
        ),
    ]
