# Generated by Django 5.2.8 on 2025-11-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_is_supplier_paid_alter_booking_booking_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ref',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
