# Generated by Django 5.2.8 on 2025-12-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_booking_supplier_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="is_consolidated",
            field=models.BooleanField(
                default=False,
                help_text="True if this entry has been included in a Daily Revenue Closing",
            ),
        ),
    ]
