# Generated by Django 5.2.8 on 2025-12-08 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ledgerentry_is_consolidated"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Flight Ticket (Amadeus)'", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique ID, e.g., 'flight_ticket'", unique=True
                    ),
                ),
                (
                    "parser_type",
                    models.CharField(
                        choices=[
                            ("none", "No Parsing (Manual Only)"),
                            ("flight_gds", "Flight GDS (Amadeus/Text)"),
                            ("hotel_voucher", "Hotel Voucher Text"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
                (
                    "manual_fields_config",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Define the manual inputs needed.",
                    ),
                ),
                (
                    "html_content",
                    models.TextField(
                        help_text="Paste your HTML template here. Use Django {{ variables }} syntax."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_text",
                    models.TextField(
                        blank=True,
                        help_text="The pasted text used for parsing (e.g. GDS/Voucher).",
                        null=True,
                    ),
                ),
                ("manual_data", models.JSONField(blank=True, default=dict)),
                ("parsed_data", models.JSONField(blank=True, default=dict)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.documenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "📄 Generated Document",
                "ordering": ["-created_at"],
            },
        ),
    ]
