# Generated by Django 5.2.8 on 2025-12-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_documenttemplate_generateddocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplate",
            name="parser_type",
            field=models.CharField(
                choices=[
                    ("none", "No Parsing (Manual Only)"),
                    ("flight_gds", "Flight GDS (Amadeus/Text)"),
                    ("hotel_voucher", "Hotel Voucher Text"),
                    ("amadeus_flight", "Amadeus Flight Lookup"),
                ],
                default="none",
                max_length=50,
            ),
        ),
    ]
