# Generated by Django 5.2.8 on 2025-12-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_documenttemplate_parser_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default", max_length=50)),
                (
                    "tinymce_api_key",
                    models.CharField(
                        blank=True,
                        help_text="TinyMCE Cloud API key (from tiny.cloud dashboard).",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Editor Settings",
                "verbose_name_plural": "Editor Settings",
            },
        ),
    ]
