# Generated by Django 5.2.8 on 2025-11-30 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_booking_booking_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Configuration", max_length=50)),
                (
                    "api_url",
                    models.URLField(help_text="e.g. https://api.ultramsg.com/..."),
                ),
                ("api_token", models.CharField(max_length=200)),
                (
                    "template_tn",
                    models.TextField(
                        default="عسلامة {client_name}،\nباش نكمّلو دوسي الفيزا، يرحم والديك عمرلنا الفورمولار هذا:\n{link}\n\nDima Voyage.",
                        verbose_name="Message (Tunisian)",
                    ),
                ),
                (
                    "template_fr",
                    models.TextField(
                        default="Bonjour {client_name},\nMerci de remplir ce formulaire pour compléter votre dossier de visa:\n{link}\n\nCordialement, Dima Voyage.",
                        verbose_name="Message (Français)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "WhatsApp Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="knowledgebase",
            options={"verbose_name_plural": "Knowledge Base"},
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(
                choices=[
                    ("ticket", "Ticket"),
                    ("outgoing_hotel", "Outgoing Hotel"),
                    ("local_hotel", "Local Hotel"),
                    ("omra", "Omra"),
                    ("trip", "Trip"),
                    ("visa_app", "Visa / Services - Application"),
                    ("visa_dummy", "Visa / Services - Dummy Booking"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="is_supplier_paid",
            field=models.BooleanField(default=False, help_text="System flag"),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="booking_type",
            field=models.CharField(
                choices=[
                    ("ticket", "Ticket"),
                    ("outgoing_hotel", "Outgoing Hotel"),
                    ("local_hotel", "Local Hotel"),
                    ("omra", "Omra"),
                    ("trip", "Trip"),
                    ("visa_app", "Visa / Services - Application"),
                    ("visa_dummy", "Visa / Services - Dummy Booking"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="is_supplier_paid",
            field=models.BooleanField(default=False, help_text="System flag"),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="category",
            field=models.CharField(
                choices=[
                    ("outgoing", "Outgoing"),
                    ("locale", "Locale"),
                    ("billetterie", "Billetterie"),
                    ("omra", "Omra"),
                    ("voyages", "Voyages organisés"),
                    ("visas", "Visas"),
                    ("autre", "Autre"),
                ],
                max_length=50,
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="escalation_contact",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Contact Escalade"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="example",
            field=models.TextField(blank=True, verbose_name="Exemple"),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="objective",
            field=models.TextField(blank=True, verbose_name="Objectif"),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="prerequisites",
            field=models.TextField(blank=True, verbose_name="Pré-requis"),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="procedure",
            field=models.TextField(verbose_name="Procédure détaillée"),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="summary",
            field=models.TextField(verbose_name="Résumé"),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="tags",
            field=models.CharField(blank=True, max_length=200, verbose_name="Tags"),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
        migrations.CreateModel(
            name="VisaApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=200, verbose_name="الاسم الكامل (باسبور)"
                    ),
                ),
                ("dob", models.DateField(verbose_name="تاريخ الولادة")),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="الجنسية"),
                ),
                (
                    "passport_number",
                    models.CharField(max_length=50, verbose_name="رقم الباسبور"),
                ),
                (
                    "passport_issue_date",
                    models.DateField(verbose_name="تاريخ إصدار الباسبور"),
                ),
                (
                    "passport_expiry_date",
                    models.DateField(verbose_name="تاريخ انتهاء الباسبور"),
                ),
                (
                    "has_previous_visa",
                    models.BooleanField(
                        default=False, verbose_name="عملت فيزا في 5 سنين اللي فاتو؟"
                    ),
                ),
                (
                    "previous_visa_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="تفاصيل الفيزا السابقة"
                    ),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="رقم الهاتف")),
                ("email", models.EmailField(max_length=254, verbose_name="الإيميل")),
                ("address", models.TextField(verbose_name="العنوان الكامل")),
                (
                    "photo",
                    models.ImageField(
                        upload_to="visas/photos/", verbose_name="صور شمسية"
                    ),
                ),
                (
                    "travel_reason",
                    models.CharField(max_length=200, verbose_name="سبب السفر"),
                ),
                ("departure_date", models.DateField(verbose_name="تاريخ الذهاب")),
                ("return_date", models.DateField(verbose_name="تاريخ الرجوع")),
                (
                    "itinerary",
                    models.TextField(blank=True, verbose_name="المدن / البرنامج"),
                ),
                (
                    "ticket_departure",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="visas/tickets/",
                        verbose_name="تذكرة الذهاب",
                    ),
                ),
                (
                    "ticket_return",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="visas/tickets/",
                        verbose_name="تذكرة العودة",
                    ),
                ),
                (
                    "travel_insurance",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="visas/insurance/",
                        verbose_name="التأمين على السفر",
                    ),
                ),
                (
                    "accommodation_type",
                    models.CharField(
                        choices=[
                            ("hotel", "فندق"),
                            ("host", "عند مستضيف"),
                            ("other", "نوع آخر"),
                        ],
                        default="hotel",
                        max_length=20,
                        verbose_name="نوع الإقامة",
                    ),
                ),
                (
                    "host_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم المستضيف"
                    ),
                ),
                (
                    "host_address",
                    models.TextField(blank=True, verbose_name="عنوان المستضيف"),
                ),
                (
                    "host_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم هاتف المستضيف"
                    ),
                ),
                (
                    "host_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="إيميل المستضيف"
                    ),
                ),
                (
                    "host_relationship",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="العلاقة بالمستضيف"
                    ),
                ),
                (
                    "hotel_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الفندق"
                    ),
                ),
                (
                    "hotel_address",
                    models.TextField(blank=True, verbose_name="عنوان الفندق"),
                ),
                (
                    "hotel_reservation",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="visas/hotels/",
                        verbose_name="نسخة من حجز الفندق",
                    ),
                ),
                (
                    "payer",
                    models.CharField(
                        choices=[
                            ("self", "أنت"),
                            ("host", "المستضيف"),
                            ("sponsor", "ضامن"),
                            ("other", "آخر"),
                        ],
                        default="self",
                        max_length=20,
                        verbose_name="شكون باش يتكفّل بالمصاريف؟",
                    ),
                ),
                (
                    "guarantor_details",
                    models.TextField(blank=True, verbose_name="تفاصيل الضامن"),
                ),
                (
                    "financial_proofs",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="visas/financials/",
                        verbose_name="وثائق إثبات الموارد",
                    ),
                ),
                (
                    "emergency_contact",
                    models.TextField(verbose_name="شخص للاتصال في الحالات الاستعجالية"),
                ),
                (
                    "consent_accurate",
                    models.BooleanField(
                        default=False, verbose_name="تأكيد صحة المعلومات"
                    ),
                ),
                (
                    "consent_data",
                    models.BooleanField(
                        default=False, verbose_name="الموافقة على جمع البيانات"
                    ),
                ),
                (
                    "consent_send_docs",
                    models.BooleanField(
                        default=False, verbose_name="الموافقة على الإرسال"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visa_data",
                        to="core.booking",
                    ),
                ),
            ],
        ),
    ]
