# Generated by Django 5.2.8 on 2025-12-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_editorsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="ref",
            field=models.CharField(
                blank=True, db_index=True, max_length=30, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="parser_type",
            field=models.CharField(
                choices=[("none", "No Parsing (Manual Only)")],
                default="none",
                max_length=50,
            ),
        ),
    ]
