# Generated by Django 5.2.8 on 2025-12-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_whatsappsettings_alter_knowledgebase_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmadeusSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Amadeus Configuration", max_length=50),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="From Amadeus Dashboard",
                        max_length=100,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        help_text="From Amadeus Dashboard",
                        max_length=100,
                        verbose_name="API Secret",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("test", "Test / Sandbox"),
                            ("production", "Live / Production"),
                        ],
                        default="test",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amadeus API Settings",
                "verbose_name_plural": "Amadeus API Settings",
            },
        ),
    ]
