# Generated by Django 5.2.8 on 2025-12-11 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_booking_ref_alter_documenttemplate_parser_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MyAssignedBooking",
            fields=[],
            options={
                "verbose_name": "My Assigned Booking",
                "verbose_name_plural": "My Assigned Bookings",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.booking",),
        ),
        migrations.AddField(
            model_name="booking",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent responsible for handling this booking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_assigned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
        migrations.AddField(
            model_name="historicalbooking",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Agent responsible for handling this booking",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_by",
            field=models.ForeignKey(
                help_text="Agent who created this booking (auto-assigned)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Agent who created this booking (auto-assigned)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
    ]
