# Generated by Django 5.2.8 on 2025-12-11 11:20

from django.db import migrations


def create_rbac_groups(apps, schema_editor):
    """Create Managers and Agents groups with appropriate permissions."""
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Get content types
    try:
        booking_ct = ContentType.objects.get(app_label="core", model="booking")
        payment_ct = ContentType.objects.get(app_label="core", model="payment")
        ledger_ct = ContentType.objects.get(app_label="core", model="ledgerentry")
        expense_ct = ContentType.objects.get(app_label="core", model="expense")
    except ContentType.DoesNotExist:
        # If content types don't exist yet, skip (shouldn't happen in normal flow)
        return

    # Create groups
    managers_group, _ = Group.objects.get_or_create(name="Managers")
    agents_group, _ = Group.objects.get_or_create(name="Agents")

    # --- MANAGERS PERMISSIONS ---
    # Get all permissions for core models
    booking_perms = Permission.objects.filter(content_type=booking_ct)
    payment_perms = Permission.objects.filter(content_type=payment_ct)
    ledger_perms = Permission.objects.filter(content_type=ledger_ct)
    expense_perms = Permission.objects.filter(content_type=expense_ct)

    # Managers get full access to everything
    managers_group.permissions.add(*booking_perms)
    managers_group.permissions.add(*payment_perms)
    managers_group.permissions.add(*ledger_perms)
    managers_group.permissions.add(*expense_perms)

    # --- AGENTS PERMISSIONS ---
    # Agents get limited booking permissions (view, add, change - no delete)
    agent_booking_perms = booking_perms.filter(
        codename__in=["view_booking", "add_booking", "change_booking"]
    )
    agents_group.permissions.add(*agent_booking_perms)

    # Agents can view payments (read-only for transparency)
    agent_payment_perms = payment_perms.filter(codename="view_payment")
    agents_group.permissions.add(*agent_payment_perms)


def reverse_rbac_groups(apps, schema_editor):
    """Remove the groups if migration is reversed."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Managers", "Agents"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_assigned_to_field"),
        ("auth", "__latest__"),
        ("contenttypes", "__latest__"),
    ]

    operations = [
        migrations.RunPython(create_rbac_groups, reverse_rbac_groups),
    ]
