# Generated by Django 5.2.8 on 2025-12-01 09:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_amadeussettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_supplier_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalbooking',
            name='is_supplier_paid',
        ),
        migrations.RemoveField(
            model_name='historicalbooking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_ledger_posted',
            field=models.BooleanField(default=False, help_text='System Flag: Ledger entries created'),
        ),
        migrations.AddField(
            model_name='booking',
            name='operation_type',
            field=models.CharField(choices=[('issue', 'Issue / New Sale'), ('change', 'Change / Modification'), ('refund', 'Refund / Cancellation')], default='issue', max_length=20, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='booking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, help_text='Link to original booking for Change/Refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='core.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('advance', 'Partial / Advance'), ('paid', 'Fully Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled (Void)')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount_client',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Refund TO Client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount_supplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Refund FROM Supplier'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='is_ledger_posted',
            field=models.BooleanField(default=False, help_text='System Flag: Ledger entries created'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='operation_type',
            field=models.CharField(choices=[('issue', 'Issue / New Sale'), ('change', 'Change / Modification'), ('refund', 'Refund / Cancellation')], default='issue', max_length=20, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Link to original booking for Change/Refund', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.booking'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('advance', 'Partial / Advance'), ('paid', 'Fully Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled (Void)')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='refund_amount_client',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Refund TO Client'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='refund_amount_supplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Refund FROM Supplier'),
        ),
        migrations.AlterField(
            model_name='amadeussettings',
            name='client_id',
            field=models.CharField(max_length=100, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='amadeussettings',
            name='client_secret',
            field=models.CharField(max_length=100, verbose_name='API Secret'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('ticket', '✈️ Air Ticket'), ('hotel_out', '🏨 Outgoing Hotel'), ('hotel_loc', '🇹🇳 Local Hotel'), ('umrah', '🕋 Umrah Package'), ('trip', '🚌 Organized Trip'), ('visa_app', 'Visa Application'), ('transfer', '🚖 Transfer'), ('dummy', '📄 Dummy Booking')], max_length=40, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='supplier_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Supplier Cost'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Sale Price / Fee'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='booking_type',
            field=models.CharField(choices=[('ticket', '✈️ Air Ticket'), ('hotel_out', '🏨 Outgoing Hotel'), ('hotel_loc', '🇹🇳 Local Hotel'), ('umrah', '🕋 Umrah Package'), ('trip', '🚌 Organized Trip'), ('visa_app', 'Visa Application'), ('transfer', '🚖 Transfer'), ('dummy', '📄 Dummy Booking')], max_length=40, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='supplier_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Supplier Cost'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Sale Price / Fee'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='accommodation_type',
            field=models.CharField(default='hotel', max_length=20),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='consent_accurate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='consent_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='consent_send_docs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='departure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='emergency_contact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='financial_proofs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='guarantor_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='has_previous_visa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='host_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='host_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='host_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='host_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='host_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='hotel_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='hotel_reservation',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='itinerary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='passport_expiry_date',
            field=models.DateField(verbose_name='تاريخ انتهاء'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='passport_issue_date',
            field=models.DateField(verbose_name='تاريخ إصدار'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='payer',
            field=models.CharField(default='self', max_length=20),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='photo',
            field=models.ImageField(upload_to='visas/photos/'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='previous_visa_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='ticket_departure',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='ticket_return',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='travel_insurance',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='travel_reason',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='whatsappsettings',
            name='template_fr',
            field=models.TextField(default='Bonjour {client_name}...\n{link}', verbose_name='Message (Français)'),
        ),
        migrations.AlterField(
            model_name='whatsappsettings',
            name='template_tn',
            field=models.TextField(default='عسلامة {client_name}...\n{link}', verbose_name='Message (Tunisian)'),
        ),
        migrations.CreateModel(
            name='FlightTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_paste_data', models.TextField(blank=True)),
                ('airline_code', models.CharField(blank=True, max_length=10)),
                ('flight_number', models.CharField(blank=True, max_length=10)),
                ('departure_city', models.CharField(blank=True, max_length=10)),
                ('arrival_city', models.CharField(blank=True, max_length=10)),
                ('real_departure_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=10)),
                ('arrival_time', models.CharField(blank=True, max_length=10)),
                ('pnr_ref', models.CharField(default='XJ9K2M', max_length=10)),
                ('live_status', models.CharField(default='Unknown', max_length=50)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='core.booking')),
            ],
        ),
    ]
