# Generated by Django 5.2.8 on 2025-12-01 10:22

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_booking_is_supplier_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("issue", "Issue / New Sale"),
                    ("change", "Change / Amendment"),
                    ("refund", "Refund / Reversal"),
                ],
                default="issue",
                max_length=20,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="refund_amount_client",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Amount we give back to client",
                max_digits=12,
                verbose_name="Refund TO Client",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="refund_amount_supplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Amount received back from supplier",
                max_digits=12,
                verbose_name="Refund FROM Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("issue", "Issue / New Sale"),
                    ("change", "Change / Amendment"),
                    ("refund", "Refund / Reversal"),
                ],
                default="issue",
                max_length=20,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="refund_amount_client",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Amount we give back to client",
                max_digits=12,
                verbose_name="Refund TO Client",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="refund_amount_supplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Amount received back from supplier",
                max_digits=12,
                verbose_name="Refund FROM Supplier",
            ),
        ),
    ]
