# Generated by Django 5.2.8 on 2025-12-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_booking_operation_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visaapplication",
            name="accommodation_type",
            field=models.CharField(
                blank=True, default="hotel", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="departure_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الولادة"),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="emergency_contact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="الاسم الكامل"
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="guarantor_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="host_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="host_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="host_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="host_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="host_relationship",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="hotel_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="hotel_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="itinerary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الجنسية"
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="passport_expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ انتهاء"),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="passport_issue_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ إصدار"),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="payer",
            field=models.CharField(
                blank=True, default="self", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="travel_reason",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
