# Generated by Django 5.2.8 on 2025-12-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_visaapplication_accommodation_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(
                choices=[
                    ("ticket", "✈️ Air Ticket"),
                    ("hotel_out", "🏨 Outgoing Hotel"),
                    ("hotel_loc", "🇹🇳 Local Hotel"),
                    ("umrah", "🕋 Umrah Package"),
                    ("trip", "🚌 Organized Trip"),
                    ("tour", "🗺️ Tours"),
                    ("visa_app", "Visa Application"),
                    ("transfer", "🚖 Transfer"),
                    ("dummy", "📄 Dummy Booking"),
                ],
                max_length=40,
                verbose_name="Service Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="booking_type",
            field=models.CharField(
                choices=[
                    ("ticket", "✈️ Air Ticket"),
                    ("hotel_out", "🏨 Outgoing Hotel"),
                    ("hotel_loc", "🇹🇳 Local Hotel"),
                    ("umrah", "🕋 Umrah Package"),
                    ("trip", "🚌 Organized Trip"),
                    ("tour", "🗺️ Tours"),
                    ("visa_app", "Visa Application"),
                    ("transfer", "🚖 Transfer"),
                    ("dummy", "📄 Dummy Booking"),
                ],
                max_length=40,
                verbose_name="Service Type",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="category",
            field=models.CharField(
                choices=[
                    ("outgoing", "Outgoing"),
                    ("locale", "Locale"),
                    ("billetterie", "Billetterie"),
                    ("omra", "Omra"),
                    ("voyages", "Voyages organisés"),
                    ("circuits", "circuits"),
                    ("visas", "Visas"),
                    ("autre", "Autre"),
                ],
                max_length=50,
                verbose_name="Catégorie",
            ),
        ),
    ]
