# Generated by Django 5.2.8 on 2025-12-02 10:31

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

def create_groups(apps, schema_editor):
    # 1. Define the Strict Roles
    roles = {
        # AGENTS: Operational Access Only
        # They will NOT see Ledger, Expenses, Suppliers, or the Payment Tab.
        "Agents": {
            "Booking": ["add", "change", "view"],       # Can sell & modify
            "Client": ["add", "change", "view"],        # Can manage customers
            "VisaApplication": ["add", "change", "view"], # Can handle visas
            "FlightTicket": ["add", "change", "view"],  # Can save flights
            "Announcement": ["view"],                   # Read-only news
            # NOTE: "Payment" is excluded here. 
            # They can still take payments via the Booking "Command Center" 
            # because that runs as a backend process, but the "Payment" sidebar tab will vanish.
        },
        
        # MANAGERS: Full Control
        "Managers": {
            "Booking": ["add", "change", "delete", "view"],
            "Client": ["add", "change", "delete", "view"],
            "Payment": ["add", "change", "delete", "view"],
            "LedgerEntry": ["add", "change", "view"],   # Financials
            "Expense": ["add", "change", "delete", "view"],
            "Supplier": ["add", "change", "delete", "view"],
            "Announcement": ["add", "change", "delete", "view"],
            "WhatsAppSettings": ["add", "change", "view"],
            "KnowledgeBase": ["add", "change", "delete", "view"],
            "AmadeusSettings": ["add", "change", "delete", "view"],
            "VisaApplication": ["add", "change", "delete", "view"],
            "FlightTicket": ["add", "change", "delete", "view"],
        }
    }

    for group_name, permissions in roles.items():
        group, created = Group.objects.get_or_create(name=group_name)
        
        # Clear existing permissions to ensure a clean slate
        if not created:
            group.permissions.clear()
            
        for model_name, perms in permissions.items():
            # Find the model content type (case insensitive)
            try:
                ct = ContentType.objects.get(app_label='core', model=model_name.lower())
                
                for perm in perms:
                    codename = f"{perm}_{model_name.lower()}"
                    try:
                        p = Permission.objects.get(content_type=ct, codename=codename)
                        group.permissions.add(p)
                    except Permission.DoesNotExist:
                        print(f"⚠️ Warning: Permission '{codename}' not found. Skipping.")
            except ContentType.DoesNotExist:
                print(f"⚠️ Warning: Model '{model_name}' not found. Skipping.")
        
        print(f"✅ Group '{group_name}' updated/created.")

def remove_groups(apps, schema_editor):
    Group.objects.filter(name__in=["Agents", "Managers"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        # This points to your last known migration
        ('core', '0013_alter_booking_booking_type_and_more'), 
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
