# Generated by Django 5.2.8 on 2025-12-03 10:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20251202_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='visa_form_config',
            field=models.JSONField(blank=True, default=core.models.default_visa_fields, verbose_name='Public Form Fields'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='visa_form_config',
            field=models.JSONField(blank=True, default=core.models.default_visa_fields, verbose_name='Public Form Fields'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK', 'Bank Transfer'), ('MOBILE', 'Mobile Money'), ('CHECK', 'Check')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK', 'Bank Transfer'), ('MOBILE', 'Mobile Money'), ('CHECK', 'Check')], default='CASH', max_length=20),
        ),
    ]
