# Generated by Django 5.2.8 on 2025-12-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_booking_visa_form_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('quote', '📝 Quote / Draft'), ('confirmed', '✅ Confirmed'), ('cancelled', '🚫 Cancelled')], default='quote', max_length=20, verbose_name='Booking Status'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='status',
            field=models.CharField(choices=[('quote', '📝 Quote / Draft'), ('confirmed', '✅ Confirmed'), ('cancelled', '🚫 Cancelled')], default='quote', max_length=20, verbose_name='Booking Status'),
        ),
    ]
