"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
import sentry_sdk
from django.templatetags.static import static  # <--- CRITICAL IMPORT FOR LOGO
from django.urls import reverse_lazy
from sentry_sdk.integrations.django import DjangoIntegration

# Initialize Sentry ONLY if a DSN is provided in .env
SENTRY_DSN = os.environ.get("SENTRY_DSN")

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        # Set to 1.0 to capture 100% of errors in development/early production
        traces_sample_rate=1.0,
        # If you use Celery later, add CeleryIntegration here too
        send_default_pii=True,  # captures user info (be careful with privacy laws)
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost").split(",")


# Application definition

INSTALLED_APPS = [
    "unfold",  # <--- NEW: Must be at the top
    "unfold.contrib.filters",  # <--- NEW: Optional, for better filters
    "simple_history",  # <--- NEW: for better activity logging
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "rangefilter",
    "core.apps.CoreConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",  # <--- NEW: Tracks the user
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL", "sqlite:///db.sqlite3"), conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Register the assets folder so Django finds your logo.png
STATICFILES_DIRS = [
    BASE_DIR / "assets",
    BASE_DIR / "core" / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- UNFOLD CONFIGURATION ---

UNFOLD = {
    "SITE_TITLE": "Dima Voyage",
    "SITE_HEADER": "Dima Admin",
    "SITE_URL": "/",
    "SITE_ICON": lambda request: static("dima_voyages.png"),
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Operations",
                "separator": True,
                "items": [
                    {
                        "title": "Bookings",
                        "icon": "airplane_ticket",
                        "link": "/admin/core/booking/",
                        "permission": lambda request: request.user.has_perm(
                            "core.view_booking"
                        ),
                    },
                    {
                        "title": "Clients",
                        "icon": "group",
                        "link": "/admin/core/client/",
                        "permission": lambda request: request.user.has_perm(
                            "core.view_client"
                        ),
                    },
                    {
                        "title": "Visa Applications",
                        "icon": "badge",
                        "link": "/admin/core/visaapplication/",
                        "permission": lambda request: request.user.has_perm(
                            "core.view_visaapplication"
                        ),
                    },
                    {
                        "title": "Suppliers",
                        "icon": "store",
                        "link": "/admin/core/supplier/",
                        "permission": lambda request: request.user.has_perm(
                            "core.view_supplier"
                        ),
                    },
                ],
            },
            {
                "title": "Finance",
                "separator": True,
                "items": [
                    {
                        "title": "Payments",
                        "icon": "payments",
                        "link": "/admin/core/payment/",
                        # The Agent Hiding Trick
                        "permission": lambda request: request.user.has_perm(
                            "core.change_payment"
                        ),
                    },
                    {
                        "title": "Ledger (Cash Flow)",
                        "icon": "account_balance",
                        "link": "/admin/core/ledgerentry/",
                        "permission": lambda request: request.user.has_perm(
                            "core.view_ledgerentry"
                        ),
                    },
                    {
                        "title": "Expenses",
                        "icon": "receipt_long",
                        "link": "/admin/core/expense/",
                        "permission": lambda request: request.user.has_perm(
                            "core.view_expense"
                        ),
                    },
                ],
            },
            {
                "title": "Support & Updates",
                "separator": True,
                "items": [
                    {
                        "title": "Announcements",
                        "icon": "campaign",
                        "link": "/admin/core/announcement/",
                        "badge": "core.utils.badge_callback",
                        "permission": lambda request: request.user.has_perm(
                            "core.view_announcement"
                        ),
                    },
                    {
                        "title": "Knowledge Base",
                        "icon": "menu_book",
                        "link": "/admin/core/knowledgebase/",
                        "permission": lambda request: request.user.has_perm(
                            "core.view_knowledgebase"
                        ),
                    },
                ],
            },
        ],
    },
}

# --- SECURITY HARDENING ---
if not DEBUG:
    # 1. Force HTTPS
    # Redirect all HTTP traffic to HTTPS
    SECURE_SSL_REDIRECT = True

    # 2. Secure Cookies
    # Ensure cookies are only sent over HTTPS (prevents theft)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # 3. Browser Security Headers
    # Prevent the browser from guessing content types (MIME sniffing)
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Enable the browser's XSS filtering (Cross-Site Scripting)
    SECURE_BROWSER_XSS_FILTER = True

    # Prevent your site from being embedded in an iframe (Clickjacking protection)
    X_FRAME_OPTIONS = "DENY"

    # 4. HSTS (HTTP Strict Transport Security)
    # Tells the browser: "Hey, ONLY ever talk to me via HTTPS for the next year"
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
