"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import dj_database_url
import os
from pathlib import Path
from django.urls import reverse_lazy
from django.templatetags.static import static # <--- CRITICAL IMPORT FOR LOGO

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ra-yvu*-q(nh%$tyhy@=oj77$$zomfxsqb+!$a!ucioesl746e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",                  # <--- NEW: Must be at the top
    "unfold.contrib.filters",  # <--- NEW: Optional, for better filters
    'simple_history',  # <--- NEW: for better activity logging
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rangefilter',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware', # <--- NEW: Tracks the user
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', 'sqlite:///db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Register the assets folder so Django finds your logo.png
STATICFILES_DIRS = [
    BASE_DIR / "assets",
    BASE_DIR / "core" / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- UNFOLD CONFIGURATION ---
UNFOLD = {
    "SITE_TITLE": "Dima Voyage",
    "SITE_HEADER": "Dima Admin", 
    "SITE_URL": "/",
    
    # Use SITE_ICON to place the image beside the text
    "SITE_ICON": lambda request: static("dima_voyages.png"),

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Operations",
                "separator": True,
                "items": [
                    {
                        "title": "Bookings",
                        "icon": "airplane_ticket",
                        "link": reverse_lazy("admin:core_booking_changelist"),
                    },
                    {
                        "title": "Clients",
                        "icon": "group",
                        "link": reverse_lazy("admin:core_client_changelist"),
                    },
                    {
                        "title": "Suppliers",
                        "icon": "store",
                        "link": reverse_lazy("admin:core_supplier_changelist"),
                    },
                ],
            },
            {
                "title": "Finance",
                "separator": True,
                "items": [
                    {
                        "title": "Payments",
                        "icon": "payments",
                        "link": reverse_lazy("admin:core_payment_changelist"),
                    },
                    {
                        "title": "Ledger (Cash Flow)",
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:core_ledgerentry_changelist"),
                    },
                    {
                        "title": "Expenses",
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:core_expense_changelist"),
                    },
                ],
            },
            {
                "title": "Support & Updates", # <--- Updated Section Title
                "separator": True,
                "items": [
                    {
                        "title": "Announcements",
                        "icon": "campaign",
                        "link": reverse_lazy("admin:core_announcement_changelist"),
                        
                        # 🔥 The Notification Badge
                        # It calls the function badge_callback() in core/utils.py
                        "badge": "core.utils.badge_callback", 
                    },
                    {
                        "title": "Knowledge Base",
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:core_knowledgebase_changelist"),
                    },
                ],
            },
        ],
    },
}
